version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_java
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  docker-from-zero-to-mastery-java:
    image: docker-from-zero-to-mastery-java
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080" 
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge