insert into person (address, first_name, gender, last_name, enabled) values ('093 Oneill Alley', 'Kaye', 'Female', 'Wasbrough', true);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Ridgeway Place', 'Koressa', 'Female', 'Gadman', false);
insert into person (address, first_name, gender, last_name, enabled) values ('704 Cambridge Plaza', 'Calhoun', 'Male', 'Staveley', false);
insert into person (address, first_name, gender, last_name, enabled) values ('22 Melvin Court', 'Mable', 'Female', 'Navarro', false);
insert into person (address, first_name, gender, last_name, enabled) values ('86619 Montana Trail', 'Rebbecca', 'Female', 'Bastock', true);
insert into person (address, first_name, gender, last_name, enabled) values ('820 Hoard Court', 'Archibald', 'Male', 'Chaim', true);
insert into person (address, first_name, gender, last_name, enabled) values ('42 Kedzie Pass', 'Westley', 'Male', 'Rosier', false);
insert into person (address, first_name, gender, last_name, enabled) values ('1 Dayton Center', 'Donalt', 'Male', 'Glasper', false);
insert into person (address, first_name, gender, last_name, enabled) values ('555 Wayridge Junction', 'Gearard', 'Male', 'Speller', true);
insert into person (address, first_name, gender, last_name, enabled) values ('5 Milwaukee Plaza', 'Abraham', 'Male', 'Maha', false);
insert into person (address, first_name, gender, last_name, enabled) values ('3935 Blue Bill Park Junction', 'Romonda', 'Female', 'Havill', true);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Heffernan Avenue', 'Cynthie', 'Female', 'Gaymar', false);
insert into person (address, first_name, gender, last_name, enabled) values ('50680 American Ash Center', 'Dannel', 'Male', 'Batisse', false);
insert into person (address, first_name, gender, last_name, enabled) values ('757 Carpenter Plaza', 'Neel', 'Male', 'Thirkettle', true);
insert into person (address, first_name, gender, last_name, enabled) values ('96 Burrows Center', 'Aldridge', 'Male', 'Luigi', true);
insert into person (address, first_name, gender, last_name, enabled) values ('7593 Aberg Street', 'Margi', 'Female', 'Ellaway', true);
insert into person (address, first_name, gender, last_name, enabled) values ('86770 Truax Center', 'Bidget', 'Female', 'Cuppitt', true);
insert into person (address, first_name, gender, last_name, enabled) values ('542 Cascade Plaza', 'Sheffie', 'Male', 'Matthews', false);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Ridge Oak Junction', 'Cairistiona', 'Female', 'Rasher', true);
insert into person (address, first_name, gender, last_name, enabled) values ('43218 Birchwood Alley', 'Birdie', 'Female', 'Dennison', true);
insert into person (address, first_name, gender, last_name, enabled) values ('79 Pepper Wood Hill', 'Mariette', 'Female', 'McCrann', true);
insert into person (address, first_name, gender, last_name, enabled) values ('3556 Linden Trail', 'Veriee', 'Female', 'Konzel', true);
insert into person (address, first_name, gender, last_name, enabled) values ('6728 Carpenter Plaza', 'Rafe', 'Male', 'Castillon', true);
insert into person (address, first_name, gender, last_name, enabled) values ('8 Pennsylvania Terrace', 'Eloisa', 'Female', 'McReidy', false);
insert into person (address, first_name, gender, last_name, enabled) values ('6914 Beilfuss Trail', 'Viole', 'Female', 'Mackieson', true);
insert into person (address, first_name, gender, last_name, enabled) values ('1779 Ronald Regan Place', 'Johny', 'Male', 'Grzegorczyk', false);
insert into person (address, first_name, gender, last_name, enabled) values ('96696 Rigney Lane', 'Randell', 'Male', 'Noli', false);
insert into person (address, first_name, gender, last_name, enabled) values ('91 Claremont Hill', 'Lowe', 'Male', 'Jacobovitch', false);
insert into person (address, first_name, gender, last_name, enabled) values ('94 Goodland Street', 'Osmond', 'Male', 'McFeate', false);
insert into person (address, first_name, gender, last_name, enabled) values ('6 Lakewood Alley', 'Georges', 'Male', 'Skeeles', true);